# nvm
source ~/.nvm/nvm.sh
nvm use 0.12

# java path

export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_60  
export JRE_HOME=${JAVA_HOME}/jre  
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib  
export PATH=${JAVA_HOME}/bin:$PATH  


